### ISSUE TITLE
testing: `testBed_.useWidgetJson()` is deprecated but still required

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#102]
The method `testBed_.useWidgetJson` has been deprecated, because using the widget specification should be the default behavior for tests.

However, there seems to be a bug, and calling `useWidgetJson` _still_ seems to be required.

**Comment by x1B** [comment]
Desired solution:
* For `master-0.x` (`v0.23.0`), we remove the deprecation warning _(this issue)._
* For `master` (`v1.0.0`), we actually change the behavior _(#149)._

**Comment by jonaswjs** [comment]
Merged for v0.23.4 and v0.24.0
