### ISSUE TITLE
testing: replace testBed with dedicated testing project

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#127]
The test bed is a bit chaotic at the moment.
We would like to have a test bed that:

* makes DOM testing simple
* makes injections (for testing and for controller) simple
* needs little boilerplate
* jasmine 2.0
* has an eventBus.flush (similar to $httpBackend, $timeout...)
* only requires laxarjs (+jasmine)
* mocks (almost) everything by default

It is not clear what would be the best way to avoid too much initialization state and still keep reconfiguration in nested `beforeEach` blocks simple.

Also, have a look at protractor.

**Comment by alex3683** [comment]
LaxarJS Testing is now available as standalone repository: https://github.com/LaxarJS/laxar-testing

Hence implemented for `v1.1.0` of LaxarJS.
