### ISSUE TITLE
integration: allow to install widgets using bower

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#129]
Apart from `laxar-path-widgets`, it should be possible to load widgets from `bower_components`, e.g. by loading from bower whenever specified in the page.json (e.g. have a "schema" `bower:`).

**Comment by x1B** [comment]
Going forward:

- There are going to be two schemes to reference any LaxarJS artifact:
   + `amd:` will be resolved using an AMD loader (for now using _require.toUrl,_ but may use another mechanism later on).
   + `file:` will be resolved depending on the artifact type (widget/theme/control), based on the corresponding LaxarJS root paths _(laxar-path-widgets aka includes/widgets, laxar-path-themes aka includes/themes and laxar-path-controls aka includes/controls).

- references to widgets and themes will default to using `file:` if nothing else is specified, while control references will default to `amd:`

- in future minor releases of LaxarJS, deprecation warnings may be added for references without type.

**Comment by x1B** [comment]
_Idea:_ We might want to add a plugin-mechanism to support user-defined lookup of artifacts.

**Comment by alex3683** [comment]
Just as discussed yesterday, we use the prefix `local:` instead of `file:`. This should emphasize, that we cannot load any file on the file system, but files locally within the application directory.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.1.0`).

### Upgrade Information

There are now two supported schemes to reference a widget from a page or a control from a widget: 

- `amd:` the reference is treated as an AMD module reference. This currently implies it is configured as a path in the product's or artifact's `require_config.js` or is directly available under the `baseUrl` for RequireJS via the provided reference. For example when using the reference `amd:ax-accordion-widget` and the `baseUrl` is set to `bower_components`, the resolved path for loading the widget descriptor will be `bower_components/ax-accordion-widget/widget.json`. If on the other hand  `ax-accordion-widget` is for example set to the path `some/where/else/accordion-widget` the widget descriptor will be loaded from the location `some/where/else/accordion-widget/widget.json`.

-  `local:`:



  `amd:` is currently the default for controls and can be omitted there. For widgets it needs to be explicitly used as prefix.
