### ISSUE TITLE
footprint: remove jquery or (if actually required) make usage explicit

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#147]
While jQuery is useful for many widgets, and required for the UiKit controls, just using LaxarJS Core (or LaxarJS Patterns) should not mandate its inclusion.
There are only a few source locations in LaxarJS Core explicitly relying on jQuery, most of which are related to testing. If more places assume jQuery implicitly (through `ng.element`) and if for this reason it cannot be removed easily, these locations must make an explicit jQuery import in their call to `require`.

**Comment by x1B** [comment]
@alex3683: plz take a look at commit 02673e8

**Comment by x1B** [comment]
## Upgrade Information

The jQuery library is no longer a mandatory runtime dependency for LaxarJS applications. Even when using the default-theme from LaxarJS UiKit, jQuery does not have to be included _unless_ widgets/controls are used that need jQuery (or jQuery UI) to function. This saves about 80kb with an _uglify2_-based build. The library is still used in widget tests, for example to load the `widget.json`.

To remove jQuery from your application's runtime dependencies, edit the `require_config.js` (or any other RequireJS configuration of your project) and make sure that there is no _deps_-entry that lists `jquery`. A _paths_-entry is no problem and indeed required for widget spec tests to run.

**Comment by alex3683** [comment]
Seems fine. Was a bit skeptic at first regarding the use of `.one` for one time event bindings, but it was obviously add in AngularJS v1.2.6 and is available since v1.3.0 in the 1.3 branch. Should be fine for LaxarJS v1.0.0.

**Comment by x1B** [comment]
_Reopen:_ not merged yet

**Comment by x1B** [comment]
Implemented on `master` (`v1.0.0`).
