### ISSUE TITLE
testing: use widget.json by default

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#149]
Currently, the `widget.json` is not used by default.
Starting with `v1.0.0`, we should change the default to `true` (use the widget.json), and make the `testBed.useWidgetJson` a no-op.

**Comment by x1B** [comment]
This ticket is used to track the _breaking change_ to the testBed default behavior.
For `master-0.x` we need to remove the current deprecation warning (#102).

**Comment by jonaswjs** [comment]
Implemented on `master` (`v1.0.0`)

### Breaking Change

When testing a widget the widget specification is used by default now. It is not necessary to call `testBed.useWidgetJson` anymore. The function is deprecated and any call can be deleted.

The widgets which did not call the function `testBed.useWidgetJson` and did not use widget specification in tests, maybe have some failing tests now. In these tests the widget configuration is not conform with the widget specification and must be adapted.
