### ISSUE TITLE
portal: angular-adapter: simplify widget module/controller naming

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#153]
Currently, the widgets and activities (and their templates), and the LaxarJS portal, use the following convention for naming AngularJS widget modules and controllers:

* Module: `widgets.somecategory.MyWidget`
* Controller: `widgets.somecategory.MyWidget.Controller`

If we allow ourselves to drop the category (because in the end it is not used for namespacing anyway), AngularJS would expect the following:

* Module: `myWidget`
* Controller: `MyWidgetController`

This removes a lot of warnings in AngularJS Batarang, and is also a bit simpler and less boilerplaty.
Namespacing will be done through prefixes (e.g. AxPopupWidget).

_Important:_ this is not supposed to be a breaking change. The old module names should remain to be supported; eventually we will add a deprecation warning.

_Addition:_ For now, widgets still have to live in a subfolder (a category) under the laxar-path-widgets (includes/widgets/ by default). It is planned to lift that restriction as well.

**Comment by x1B** [comment]
### Availability

Merged into `master` (`v1.0.0`) and `master-0.x` (`v0.23.0`).

### Upgrade Information

The pattern for naming bower _widget packages_ and AngularJS _widget modules_ and _controllers_ has changed, as described below. The old formats will continue to work for now. They will be deprecated in the future (probably with `v1.0.0`).

For a widget named `MyWidget` in category `cat` the following naming rules apply:

|                                 | old style                          | new style
|---------------------------------|------------------------------------|----------------
| GitHub repository               | `cat/my_widget`                    | `cat/my-widget`
| includes/widgets/…              | `cat/my_widget`                    | `cat/my-widget`
| bower package name              | `widgets.cat.my_widget`            | `cat/my-widget`
| (…).createControllerTestBed(…)  | `widgets.cat.my_widget`            | `cat/my-widget`
| CSS widget class                | `my-widget`                        | `my-widget`
| AngularJS module name           | `widgets.cat.my_widget`            | `myWidget`
| AngularJS controller name       | `widgets.cat.my_widget.Controller` | `MyWidgetController`

Do note that the _category is not a namespace_ (and never has been), due to the flat AngularJS injection namespace, and the flat css class namespace. For namespacing, use of _prefixes_ is encouraged. This also allows (GitHub) forks of a given widget to keep the same CSS classes and AngularJS artifact names, while being in a different category.

Also, note that for the first four entries, both dashes and underscores have already been supported as word separators and still are. The style change refers to the change in the LaxarJS grunt-init tasks for preparing artifacts:

* https://github.com/LaxarJS/grunt-init-laxar-activity/issues/5
* https://github.com/LaxarJS/grunt-init-laxar-activity/issues/6
* https://github.com/LaxarJS/grunt-init-laxar-widget/issues/5
* https://github.com/LaxarJS/grunt-init-laxar-widget/issues/6

**Comment by jpommerening** [comment]
This is great! :sparkles: :clap:
