### ISSUE TITLE
i18n: Support fallback locales

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#156]
LaxarJS should support fallback locales. For example if a application uses the locale 'en-US' the fallback should be 'en'.

**Comment by x1B** [comment]
This change allows widgets and applications to be compliant with the recommendations in [RFC-5646](http://tools.ietf.org/html/rfc5646), section 4.1 _("Choice of Language Tag")._

> For example, 'de' might suffice for tagging an email written
          in German, while "de-CH-1996" is probably unnecessarily
          precise for such a task.

**Comment by x1B** [comment]
Implemented on `master`  (`v1.0.0`) and `master-0.x` (`v0.25.0`).
