### ISSUE TITLE
bower: mark as AngularJS 1.3.x compatible

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#158]
LaxarJS seems to be working just as well with AngularJS 1.3

For 0.x we should allow both 1.2.x and 1.3.x, and for 1.x we should enforce 1.3.x (that allows to remove some code, for example in UiKit).

**Comment by x1B** [comment]
_Marking question:_ It turns out that there are incompatible changes between AngularJS `1.2.x` and `1.3.x` that may effectively prevent us from supporting both versions of AngularJS, especially with UiKit See [laxar_uikit#97](/LaxarJS/laxar_uikit/issues/97) and  [laxar_uikit#98](/LaxarJS/laxar_uikit/issues/98 for details.

**Comment by x1B** [comment]
_Unmarking question:_ we'll drop support for ng 1.2 with LaxarJS 1.0, making this part of the 1.0 milestone.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0-alpha.3`).

## Breaking Change
LaxarJS now uses AngularJS 1.3.15 and thus comes with all its breaking changes. See here for the migration guide from AngularJS 1.2.x to 1.3.x: https://code.angularjs.org/1.3.15/docs/guide/migration
