### ISSUE TITLE
flow: remove place.triggerBrowserReload

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#159]
There is a "feature" where places can cause the FlowController to perform a browser reload before navigating to them.

This has only been maintained to counter some cases of MSIE8 memory leaks and appears to be somewhat buggy anyway.

Support should be dropped for the next major to simplify the navigation handling.

**Comment by x1B** [comment]
Currently, theme changes are implemented by means of a browser reload. There is probably another way to achieve that -- need to find out.

**Comment by x1B** [comment]
_Marked question:_ LaxarJS should possibly drop the changeThemeRequest and have widgets handle this. We just need to clarify if and how to persist the current theme (local storage?) so that LaxarJS uses it when instantiating the widgets.
As an alternative, the application configuration could simply make this decision any way it likes.

**Comment by x1B** [comment]
_Answer:_ drop theme switching support (see #182).

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).

### Breaking Change

The support for `triggerBrowserReload` was completely removed. If this feature is still required, this must be implemented locally within an application.
