### ISSUE TITLE
portal: upgrade jjv and jjve dependencies

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#164]
Before `v1.0.0`, we should upgrade to the latest JSON schema validator versions.

See also #41

**Comment by alex3683** [comment]
jjv is already up-to-date. For jjve I'd like to wait until this Pull Request is accepted and merged: https://github.com/silas/jjve/pull/7

**Comment by alex3683** [comment]
jjve is now released in version 0.5.0 and supports the format property.

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).
