### ISSUE TITLE
widget_adapters: use new style module name syntax in plain adapter

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#169]
_x1B:_ The _plain_ widget adapter still uses old-style widget module names (e.g. `widgets.category.my_widget`).
It should be changed to work with new-style names (jsut `myWidget`) instead.
Because there is no significant number of plain-integrated widgets, support for the old style should simply be removed at the same time.

**Comment by x1B** [comment]
Fixed on `master` (`v1.0.0`).
Not applicable to `master-0.x`.
