### ISSUE TITLE
documentation: broken link in documentation about events

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#172]
In the file docs/manuals/events.md the link `EventBus API documentation` in the follwing section is broken:

`This information should help to get started with the event bus and intentionally omits a lot of details. For full information, refer to the EventBus API documentation.`

**Comment by x1B** [comment]
Fixed on `master` (`v1.0.0`) and `master-0.x` (`v0.26.0`).
The bug has never been released.
