### ISSUE TITLE
documentation: refer to open source widgets instead of "portal/..."

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#176]
Code samples in _[Writing Pages](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/writing_pages.md)_ and _[Writing Compositions](https://github.com/LaxarJS/laxar/blob/master/docs/manuals/writing_compositions.md)_ still refer to the "portal"-widgets.

These should be replaced with our newly open-sourced widgets.

**Comment by x1B** [comment]
After renaming the widget references in the examples, there are still some mentions of _portal_ left in the docs. For this, we'll need #177 and LaxarJS/grunt-laxar#29.

Implemented on `master` (`v1.0.0`).
