### ISSUE TITLE
tests: base q_mock on latest kriskowal q

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#194]
The tests currently use a very old version of the q_mock based on kriskowal/q. A major shortcoming of that version is that unhandled rejections are logged immediately before being handled, which leads to confusing test output.

We should either address this issue or upgrade the q_mock to be a fork of kriskowal/q 1.3+

**Comment by x1B** [comment]
_Marking Question:_ We may want to close this issue, and instead just embed the latest q within _laxar-testing_.

**Comment by alex3683** [comment]
ACK :)

**Comment by x1B** [comment]
_Closing wontfix for now._ This will be superceded by the new _laxar-testing_ work.
