### ISSUE TITLE
provide laxar as npm package

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#198]
Starting with `v1.0.0-alpha.11`, we want to publish LaxarJS core on the npm registry.

**Comment by x1B** [comment]
@jpommerening plz have a look at commit 5d688a2

**Comment by jpommerening** [comment]
@x1B Looks good to me – go ahead and `npm publish` it! :+1:

Already tried to use this in `grunt-laxar`. Works like a charm :sparkles:
