### ISSUE TITLE
"plain" technology adapter: provide additional injections

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#221]
Currently the `plain` adapter provides the context (`$scope` in angular terms), eventBus and features as injections. It would be nice if authors of plain widgets and activities had easy access to additional injections, such as the flow service and maybe some of the runtime services defined `lib/runtime/runtime_services.js`. Even though they are currently implemented with AngularJS they should work just fine in plain activities or widgets.

Also, the set of available injections should be documented ;)

**Comment by alex3683** [comment]
Implemented on `master` (`v1.1.0`).

## Upgrade Information

Documentation will follow with LaxarJS/laxar#228.

These services are now available to plain widgets in addition to those already there:
- axFlowService
- axHeartbeat
- axTimestamp
- axGlobalEventBus
- axConfiguration
- axI18n
- axFileResourceProvider
- axThemeManager
- axLayoutLoader
- axCssLoader
- axVisibilityService

**Comment by jpommerening** [comment]
Thanks!
