### ISSUE TITLE
documentation: add documentation for specific widget adapters

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#228]
Currently there is only documentation on writing adapters and much documentation about widgets, their lifecycle and other, more general things (events etc.).
What's missing is documentation targeting writing widgets for an adapter supporting a specific technology (for now AngularJS and plain JavaScript).
This is somewhat related to LaxarJS/laxar#221

**Comment by alex3683** [comment]
I will add documentation for the additional services from LaxarJS/laxar#221 later :)

**Comment by jpommerening** [comment]
Looks good to me
Pretty helpful as well :+1:

**Comment by alex3683** [comment]
Implemented on `master` (`v1.1.0`).
