### ISSUE TITLE
Allow Cancellation of debounced functions

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#241]
`ax.fn.debounce` allows asynchronous debouncing of frequent calls to one function. The problem here is, that a debounced function call may get scheduled during the lifetime of a widget, but gets executed when the widget was just removed from the page (for AngularJS the `$destroy` event occurred). This may result in JavaScript errors (`undefined` scope properties etc.).

A possible solution is to add a cancellation method to the debounced version of a function and call it when the `$destroy` event arrives.

**Comment by x1B** [comment]
Marking as *enhancement:*
`ax.fn.debounce` is a direct port of `underscore.debounce`, which does not support cancellation. With the underscore version, the user would check from within the callback if execution must be cancelled. This is also possible with the current version.

**Comment by x1B** [comment]
Implemented on `master` (`v1.2.0`).

### Upgrade Information

The wrapper function produced by `ax.fn.debounce` now provides a new method `cancel()` that can be used to cancel any pending debounced call for the wrapper.

Also, `ax.fn` now provides two new tooling APIs that should be overriden from tests if they need control over debounce behaviour and scheduling:

- `ax.fn._setTimeout` is just a wrapper for `window.setTimeout`
- `ax.fn._nowMilliseconds` is a wrapper for `Date.now`
