### ISSUE TITLE
tooling: provide Promise factory for other LaxarJS libraries

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#242]
Currently LaxarJS Core, Patterns and UiKit are based on AngularJS and use `$q` whenever Promises are needed. In principle this is fine, but it is not without problems:
In order to gain access to `$q` LaxarJS Patterns for example uses the AngularJS Injector-mechanism: 
```js
var $q = ng.injector( [ 'ng' ] ).get( '$q' );
```
Unfortunately the `$q` instance returned here is not mockable by AngularJS Mock and as a consequence tests using affected libraries will fail.

To mitigate this problem once and for all, and additionally abstract away from a concrete Promise factory, LaxarJS should provide a tooling factory function for Promises. For now it should simply return the correct, mockable `$q`.

**Comment by x1B** [comment]
Implemented on `master` (`v1.2.0`).

### Upgrade Information

A new tooling API `laxar._tooling.provideQ()` has been added. Library authors can use this API to provide a $q-compatible Promise factory that will be mocked correctly in widget tests.

Testing libraries such as `laxar/laxar_testing` (`>= 1.2.0`)and `laxar-mocks` (`>= 0.7.0`) will mock this API automatically. Any other testing code should override the method to return a suitable $q-like implementation that works for testing.
