### ISSUE TITLE
tooling: add page inspection API

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#247]
For the new page inspection feature of the laxar-developer-tools-widget, we'll need to add some APIs. The added APIs should provide access to the current page configuration (after resolving compositions and features), and to the schema of each widget.

**Comment by alex3683** [comment]
Looks good to me!

**Comment by x1B** [comment]
Implemented on `master-1.x` (`v1.2.0`).

**Comment by x1B** [comment]
Implemented for `1.x`, still needs to be merged for `master` (`v2.0.0`).

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`) and `master-1.x` (`v1.2.0`).
