### ISSUE TITLE
tooling: tests not executed by karma task

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#255]
The tests are not included in the karma task for LaxarJS 1.2.x. Thus they don't run in the Travis build and a currently existing error isn't detected.

**Comment by x1B** [comment]
To be fixed on:
  - `master-1.x`
  - `release-1.2.x`

**Comment by x1B** [comment]
Fixed on `master-1.x` (`v.1.3.0`) and `release-1.2.x` (`v.1.2.1`).
