### ISSUE TITLE
Remove any legacy and compatibility code

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#273]
For example, the widget loader does much stuff to support widgets with a deprecated descriptor format. Moreover it assumes, that the default integration technology is `angular`, which will clearly change from v2.0.0 onward. 
There are certainly more of these things buried within the code.

**Comment by x1B** [comment]
I think that there are several outdated locations that are being searched for CSS and/or HTML assets. CssLoader, LayoutLoader etc. are good candidates for cleanup.

**Comment by x1B** [comment]
See also #305

**Comment by x1B** [comment]
Changes (collecting here for the Changelog info):
- [ ] no defaults for the `integration` entry of the `widget.json` anymore (type and technology *must* be specified).
