### ISSUE TITLE
Documentation: Fix broken link in infrastructure_and_tools.md

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#284]
The url of the link `LaxarJS flow` is `"./flow_and_pages.md"` but should be `"./flow_and_places"`.

Paragraph of the source file `docs/manuals/infrastructure_and_tools.md`:
```
  * The `ngView` directive integrates the [$ngRoute](https://docs.angularjs.org/api/ngRoute)-service, which the [LaxarJS flow](./flow_and_pages.md) uses for URL routing.
```

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`) and `release-1.x` (`v1.2.5`).
