### ISSUE TITLE
Merge namespaces for widget ids and composition ids

### ISSUE THREAD

**Issue by FabianEmmes** [LaxarJS/laxar#289]
Currently namespaces for widget ids and composition ids are treated separately in page description files. This separation leads to needlessly complicated code.

Also, using the ``laxar-developer-tools-widget`` seems to not treat the namespaces differently and shows a circular dependency for the composition in the following page description:
```json
{
   "layout": "application",
   "areas": {
      "contentA": [
         {
            "id": "test",
            "widget": "someWidget",
            "features": {}
         }
      ],
      "test.area": [
         {
            "composition": "someComposition",
            "id": "test"
         }
      ]
   }
}
```

Using only one namespace for widget ids and composition ids has the following pros and cons, as far as I can tell:

Pros:
- Simpler code in Laxar
- Simpler invariant for the Laxar user
- Resolves the described problem in ``laxar-developer-tools-widget``

Cons:
- Breaking change: If there are pages with colliding widget/composition ids, they need to be upgraded.

**Comment by FabianEmmes** [comment]
A proposed solution is in #290

**Comment by x1B** [comment]
Redeclaring this as a *bug*:

The following page definition currently leads to undefined behavior, because the ID collision is not detected:

```json
{
   "layout": "application",
   "areas": {
      "content": [
         {
            "id": "A",
            "widget": "someWidget-providing-area-X"
         },
         {
            "id": "A",
            "composition": "someComposition-providing-area-X",
         }
      ],
      "A.X": [ { "widget": "...." } ]
   }
}
```

**Comment by x1B** [comment]
Fixed on `master-1.x` (`v1.3`) and `release-1.2.x` (`v1.2.4`).
