### ISSUE TITLE
provide axLog injection for widgets

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#306]
Widgets should be provided with an `axLog` injection so that they do not need to call the global logger, which is deprecated with #303.
Also, this `axLog` injection can inject useful context into log messages (e.g. the widget name and ID).

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`).

The logging service for widgets (`axLog`) also adds the widget's name and id to each log message for improved debugging. Additionally the global logger without any special widget adaptions is available as `axGlobalLog`.

**Comment by alex3683** [comment]
We still want to implement two things with this ticket:

1. Remove the global log as property of laxar (i.e. `laxar.log`)
2. Add log to the widget context object

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`).

The logging service for widgets (`axLog`) also adds the widget's name and id to each log message for improved debugging. The global logger without any special widget adaptions is available as `axGlobalLog`.
Additionally `axLog` is available as property `log` on the widget context object (`axContext`).
