### ISSUE TITLE
event bus: remove default error logger and always use laxar logging

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#327]
The default error logger of the event bus was always instantly overwritten with the laxar internal global log instance. Since this will always be the way to go, we can simply pass in the log instance as an argument to the `create` function.

This was previously marked as task for issue #310.

**Comment by x1B** [comment]
Also as part of this ticket: remove the eventbus-specific configuration object, use the normal LaxarJS configuration instead.

**Comment by x1B** [comment]
Removing *breaking* label, as the event bus `create` method is (currently) not a public API.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
