### ISSUE TITLE
configuration: allow configuration of instance id factory function

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#328]
In order to allow more complex instance ids the factory function for these ids needs to be configurable.

This was previously marked as task for issue #310.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### Upgrade Information

There is a new configuration option `logging.instanceId` to control if and how instance IDs are generated and used as log tags for a LaxarJS application instance. By default (`null`), an ID is generated when bootstrapping a LaxarJS instance by concatenating the current integer timestamp (millisecond precision) with a random number from '0' - '99'.
The configuration value can be set to a function returning a string that should be used instead, or to a boolean `false`
