### ISSUE TITLE
timer: remove `resumedOrStarted`

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#347]
In the past, page navigation sometimes encompassed a full page reload. For this reason, the resumedOrStarted method was added to the timer, at that time.
The method and the associated timer persistence should no longer be needed.

**Comment by x1B** [comment]
The timer mock should be cleaned up as well.

**Comment by alex3683** [comment]
And there should be some tests for the timer itself.

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`)
