### ISSUE TITLE
documentation: add a manual for the plain widget adapter

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#348]
There might not be much to say, but at least the `onDomAvailable` hook and the `axWithDom` service need to be documented somewhere.

**Comment by x1B** [comment]
@alex3683 care to have a look at [the new plain adapter manual](https://github.com/LaxarJS/laxar/blob/feature/348-manual-on-plain-adapter-rebase/docs/manuals/plain_adapter.md#the-plain-integration-technology)?

**Comment by alex3683** [comment]
@x1B  Told you all hints and errors already verbally. Apart from that, looks good 👍🏻

**Comment by x1B** [comment]
@alex3683 Thx.

Implemented on `master` (`v2.0.0`).
