### ISSUE TITLE
cleanup MSIE9 support

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#349]
For v2.0, we'll be dropping MSIE9 support. MSIE10 will be the new baseline. However, users should still be able to run LaxarJS on MSIE9 by pulling in additional polyfills.
Going forward, whenever we consciously break compatibility, we should add infos to the _upgrade information_ that explains how MSIE9-compatibility could be restored (by adding a polyfill or a transpile step).

The objective of _this_ issue is identification and removal of current MSIE 9 compatibility code and polyfills.

**Comment by x1B** [comment]
For instance, the MSIE9 stylesheet-limit workaround may be removed from the CSS loader: https://github.com/LaxarJS/laxar/blob/master/lib/loaders/css_loader.js

**Comment by alex3683** [comment]
Implemented on `master` (`v2.0.0`).

### Breaking Change

All workarounds and hacks to support Microsoft Internet Explorer <= 9 were completely removed. The commit for this issue removed the final hack mentioned by @x1B . To be able to still use IE9 for this case it is advised to also use the merged CSS file during development. This will prevent the stylesheet limit to pop up.

**Comment by jpommerening** [comment]
I think there's still one spot in the README that needs to be updated: https://github.com/LaxarJS/laxar/blob/master/README.md#requirements 🤓
