### ISSUE TITLE
Use "assetUrl" instead of "assetUrlForTheme" when loading a theme's theme.css

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#352]
When implementing #304, we expected themes to have "themed assets" (assets that can be loaded with `assetForTheme` or `assetUrlForTheme`), as can be seen in the test data (link below). Now, while implementing the webpack loader that generates the artifact listing, I noticed a small inconsistency: the `theme.css` is not inside a "themed" subdirectory of the theme artifact (because that would not make any sense at all), so we should just use `assetUrl` instead of `assetUrlForTheme` and adjust the structure of the artifact listing accordingly.

This probably affects only the [theme loader](/LaxarJS/laxar/blob/ad07bc57ed21d1f86cbf7b73db0cfa5c9f7b9b79/lib/loaders/theme_loader.js#L4) and associated [test data](/LaxarJS/laxar/blob/ad07bc57ed21d1f86cbf7b73db0cfa5c9f7b9b79/lib/runtime/spec/data/artifact_data.js#L22).

This change is incremental to #304 and (since that change has not been released yet) I'd suggest to not write a changelog entry for this issue.

/cc @alex3683, @x1B

**Comment by x1B** [comment]
@jpommerening I presume this can be closed?

**Comment by jpommerening** [comment]
Oh, yes, merged it already.
