### ISSUE TITLE
object.path aborts on empty path segment

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#369]
The utility function `object.path` aborts processing if the path contains an empty segment (e.g. when ending with `.` or containing `..`).
Instead, the empty string should be used as key.

*Edit:* the current behavior is being relied upon in other artifacts. For this reason, this issue is now just about spec'ing and documenting the status quo.

**Comment by x1B** [comment]
@alex3683 should we fix this for `master-1.x` and `release-1.2.x` as well? Or do you think it's too risky (e.g. for projects that might be relying on the current buggy behavior)?

**Comment by alex3683** [comment]
Hm, I'd say its clearly a bug and am pretty sure nobody relied on this behavior. So be brave :)

**Comment by x1B** [comment]
After some more inspection, there seem to be places that rely on the current behavior. So for legacy reasons, we should stick to the old ways, and improve docs & spec coverage instead.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0`), `master-1.x` (`v1.3.0`) and `release-1.2.x` (`v1.2.9`).
