### ISSUE TITLE
2.x: move from jjv to ajv for JSON schema validation

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#380]
We're currently running into issues with [jjv](https://github.com/acornejo/jjv), especially with bugs in the handling of non-primitive defaults. It seems like the project is inactive, so we're left with the option to either fork or replace jjv as a dependency.

It looks like [ajv](http://epoberezkin.github.io/ajv/) might be a fast and well-documented option for a replacement.

**Comment by x1B** [comment]
Note that the error-handling of ajv is a bit peculiar: errors are stored on the validator and are overwritten each time a validation is performed. We should probably make a deep copy of any errors in our validation wrapper.

**Comment by x1B** [comment]
@jpommerening @alex3683 

Update after some reconsideration: since the ajv-library is quite heavyweight, we should investigate pre-validating all schemata at load-time (using a webpack loader that employs e.g. ajv). This would also automatically encompass the work done in #292

This approach has multiple benefits:

 - no validation required at runtime (small to medium performance boost, depending on the application size),
 - smaller JS footprint (1kb page.js would become our sole dependency),
 - possibly smaller assets bundle (schemata can be omitted),
 - (possibly) more helpful error reporting on the command-line, since the webpack loader environment is available (for printing physical file paths etc.).

Then, there are the following drawbacks:

 - tooling even more important (with the assets bundle we are going down that road anyway),
 - in some cases, the expansion of defaults can *increase* bundle size,
 - we need to come up with a way to make the schema information available to development tools at runtime (e.g. for page-inspection).

**Comment by alex3683** [comment]
Quick note on your last drawback:
Perhaps schema information should be available for tooling api via a separate request and not bundled with the application. This would keep the main bundle clean and development and release builds consistent. I didn't think this through, but just wanted to write it down  ✏️ 💾

**Comment by jpommerening** [comment]
Sounds good. Maybe we could simplify things for our users (regarding webpack setup etc) if we incorporate the validation and defaults expansion into `laxar-tooling`?
The tooling library _already_ works with all the JSON files and generates the artifacts module. It should be easy to slip ajv or jjv in there somehow. The schemas for widget features are easily accessible since we already load the `widget.json` files anyway and the schemas for pages and flows can be loaded via the callback option that's already present.

**Comment by x1B** [comment]
Yes, I like both of these ideas. *If* loading the schemas for development is too slow or if it is too hard to learn about the correct paths, we can think about having a separate tooling-bundle.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

JSON schema processing as well as composition assembly has been moved from the LaxarJS runtime (more specifically, from the page and widget loaders and from the flow controller) to the laxar-tooling build infrastracture.

This improves page load performance and reduces the LaxarJS library footprint by eliminating the `jjv` and `jjve` dependency. Also, this allows us to use the big but very feature-rich `ajv` schema processor. Validation problems are now reported by laxar-tooling, but if the webpack-dev-server is used, they will still show up in the Browser console.
