### ISSUE TITLE
flow: ensure that redirects don't mess with browser history

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#382]
Currently, you can run into situations where the back button is not working correctly after a redirect. This should be simple to fix by using `$location.replace()` (v1.x). For 2.x, we need to check if this problem exists with page.js before closing this issue.

**Comment by alex3683** [comment]
This issue will be closed, since the problem could not be reproduced on 1.x. If this problem comes up again, please open a new issue.
