### ISSUE TITLE
css loader: remove

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#385]
Since webpack includes all css files in its bundle (in development mode), this module is irrelevant. Remove! 🐜❗️

**Comment by jpommerening** [comment]
Note: this requires webpack to be setup a specific way. You *must* use the _style-loader_ to inject the styles in debug mode. Just using a loader that spits out raw CSS will not work anymore.

2nd note: without the css loader, the control loader can probably be removed as well

**Comment by x1B** [comment]
@jpommerening if I configure webpack to use the extract-text-plugin instead of the style loader, it should also work, right?

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### BREAKING CHANGE

The CSS-loader was removed from the LaxarJS runtime. Projects should configure Webpack with the `laxar-loader`, the `css-loader` and either the `style-loader` (development) or the `extract-text-plugin` (production) to load their artifact's CSS assets.
