### ISSUE TITLE
cleanup: object.extend, object.deepFreeze

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#395]
- object.extend can be removed (users should use ES2015 spread or object.options)
- object.deepFreeze is not actually used (there is a reference in the event bus, but that is obscure and should be cleaned up)

**Comment by jpommerening** [comment]
@x1B: have a look at this low hanging fruit? 🔍
Link: https://github.com/LaxarJS/laxar/compare/feature/395-remove-object-extend-and-deepFreeze

**Comment by x1B** [comment]
@jpommerening maybe I'm missing something, but deepFreeze still seems to be alive and well in that commit?

**Comment by jpommerening** [comment]
Whoopsie.

**Comment by x1B** [comment]
:+1:

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0`)

### Breaking Change

- `object.extend` and `object.deepFreeze` have been removed.  
  If you are using `object.extend()`, either replace calls with `Object.assign()` or ES7 object spread notation (if either is supported by your runtime), or implement it yourself.
- EventBus subscribers that request event data to *not* be cloned (`{ clone: false }`), will not receive frozen event objects anymore.
