### ISSUE TITLE
widget adapters: remove need for redundant technology field in bootstrapped adapter factory

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#396]
A widget adapter currently needs to define the supported technology twice: Once on module level and once in a bootstrapped adapter factory instance. The latter is only needed, because the widget loader gets a flat list of those factory instances and needs to map these to their respective technology itself. Instead that map could directly be passed in by `laxar.bootstrap`, which already has this map at hand.

**Comment by jpommerening** [comment]
@alex3683, guess you're busy atm, so I'm giving this @x1B for review 🕵️

**Comment by x1B** [comment]
@jpommerening LGTM -- note that I landed some bigger commits throughout the last days, so your might need to revisit some things during rebase/merge.

**Comment by jpommerening** [comment]
Merge went well except for your "TODO: remove" comment ;)

Implemented on `master` (`v2.0.0`)

**Comment by x1B** [comment]
### Upgrade Information

Widget adapters no longer need to provide their technology identifier from all instances.
Exporting it once on module level is sufficient.
