### ISSUE TITLE
widget adapters: move adapter errors from widget loader into separate module

### ISSUE THREAD

**Issue by alex3683** [LaxarJS/laxar#397]
The widget loader module provides a set of error factories for typical errors that may occur in a widget adapter. Thus adapters know about the widget loader although they only need some static helper functions. Not only will that require documenting the otherwise internal widget loader, but additionally might open the door for hacky access to the loader, we didn't intend to happen.
Hence these factories should move into a separate module that only provides such optional utilities for widget adapters.

**Comment by x1B** [comment]
_Marked breaking:_ This will remove the widgetLoader from the LaxarJS services.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
