### ISSUE TITLE
tooling: add browser extension integration

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#403]
For LaxarJS v1.3.0, we prepared an integration channel to inform the developer-tools-web-extension about the current page and its events. This work needs to be transferred to LaxarJS v2.

**Comment by jpommerening** [comment]
A lot going on here :eyes:

For now, a breaking change has been avoided, at least in the area around #442.
The `axTooling` injection still has its `.pages` property, which still has the same API.

If we run short of time, we can simple port [`lib/tooling/external_api.js`](https://github.com/LaxarJS/laxar/blob/master-1.x/lib/tooling/external_api.js) to the current master branch.

We will not be able to handle multiple instances or bootstrapping items in that case.

**Comment by jpommerening** [comment]
Pushed [feature/403-add-devtools-extension-api](https://github.com/LaxarJS/laxar/compare/feature/403-add-devtools-extension-api). Works out-of-the-box with the current extension.

**Comment by alex3683** [comment]
I'm fine with this.

**Comment by jpommerening** [comment]
Implemented on `master`

Additionally, I opted to initialize the `pageInfoVersion` with the current timestamp, so reloads of the page cause an update in the developer tools extension view.

**Comment by x1B** [comment]
Nice catch, this might event solve LaxarJS/laxar-developer-tools-web-extension#3
