### ISSUE TITLE
documentation: add tooling API

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#404]
Once the tooling API is finalized (e.g. #359, #403), we should to make sure that the generated API docs contain our tooling docs.

**Comment by jpommerening** [comment]
Implemented on `master` (via #442)

Docs are here:
- https://github.com/LaxarJS/laxar/blob/master/docs/api/tooling.tooling.md
- https://github.com/LaxarJS/laxar/blob/master/docs/api/tooling.pages.md
