### ISSUE TITLE
handle errors thrown in domAttachTo

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#408]
Somewhere around here: https://github.com/LaxarJS/laxar/blob/master/lib/runtime/area_helper.js#L154

For example: If my JSX contains errors, probably due to my inability to correctly type `dangerouslySetInnerHTML`, much less use it as intended, I might get runtime errors when `laxar-react-adapter` calls `ReactDom.render`. This happens as part of `domAttachTo`.

The result is that (at best) the Promise polyfill warns me about unhandled rejections without much of a hint to what went wrong. We should probably make that method of the area helper return the result of that `Promise.all()` chain and carry the result as far up the call chain as necessary.

**Comment by alex3683** [comment]
Fixed on `master` (`v2.0.0`).
