### ISSUE TITLE
Finish API-doc for v2.0

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#418]
Most of the API doc work for v2.0.0 has already been done. This is just for cleanup/finishing touches.

**Comment by x1B** [comment]
@jpommerening since @alex3683 and myself wrote almost all of the current API doc, could you maybe have a look at it and make recommendations for improvements?

**Comment by x1B** [comment]
We might want to update code examples in API doc to not using AMD, just because it tends to make things look complicated.

**Comment by alex3683** [comment]
And change examples to ES2015 syntax for conciseness.

**Comment by jpommerening** [comment]
Phew, that's a lot to look at :wow:
I wish there was a better way to read it than crawling through the MD files on GitHub *\*hint\**  @jonaswjs 

But, I was lucky already and noticed something:
- https://github.com/LaxarJS/laxar/blob/master/docs/api/runtime.widget_services.md
  `isVisible` appears as a module member but is actually a member of the `axAreaHelper`.

I'll update this comment as I keep on RTFM.

**Comment by alex3683** [comment]
Issues found:
- [ ]  In `event_bus_mock.js`: `@memberof {EventBusMock}`➡️ `@memberof EventBusMock`
- [ ]  In `laxar-widget-service-mocks.js`: All `@memberof` at module level should be deleted. Module members are automatically detected and otherwise `laxar-widget-service-mocks` is added as a type (which it isn't).

**Comment by jpommerening** [comment]
For now, I'll unassign this issue. I've seen no total blunders.

**Comment by x1B** [comment]
Alright, I'll bite the bullet and try to fix these.

**Comment by x1B** [comment]
For now I'll leave out grouping of docs by testing/runtime/… - it sounds like a good idea, but I have no idea how much work this would be. Also, to _users_ of the LaxarJS API, the structure of the directories should be irrelevant, since nothing inside of `lib/` is public API under _semver._

Their only entry points into the versioned API should be:

- `docs/api/laxar.md`,
- `docs/api/runtime.widget_services.md`,
- `docs/api/laxar-widget-service-mocks.md`

and stuff reachable from there using links.


We should probably highlight these entry points in the manuals or even the README.md
Maybe we could add an always-on-top `index.md` (like for the manuals).

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

**Comment by x1B** [comment]
Oh, forgot to touch the code examples (AMD -> ES2015)…
Creating a followup issue.
