### ISSUE TITLE
i18n: allow instantiating i18n without an i18n feature

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#429]
Currently, widgets need to have (at least) an `i18n` feature to use the `axI18n` injection, because it creates an API `forFeature( 'i18n' )` by default.

This in turn leads to controls not being able to use the `axI18n` from the `axWidgetServices` of such a widget. See LaxarJS/ax-input-control#29 for a case where this is a problem. We could change the service to use the global Laxar configuration if the widget does not have its own `i18n` feature.

**Comment by jpommerening** [comment]
Oh, the whole uikit i18n thing needs to be updated as well. Yay.

**Comment by x1B** [comment]
@jpommerening Are you looking for review/input on this, before landing? Or do we need to make additional changes? I'd be happy to review/land in order to get started on LaxarJS/laxar-angular-adapter#38

**Comment by jpommerening** [comment]
I think this is good to go, only missing a changelog. Want to have a look, make any adjustments you need for the ticket you mentioned and release it?

**Comment by x1B** [comment]
Sure, will do

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).

### Upgrade Information

So far, the widget service `axI18n` could only be injected if the receiving widget had feature configuration for the feature `i18n`.
To use LaxarJS i18n, it is still recommended for widgets to declare the `i18n` feature. However, in some cases widgets actually do not mean to support i18n, but still require access to the `axI18n` service. For example, an AngularJS widget may be using controls that access i18n information to support the localized parsing/formatting of values.
From now on, axI18n may be injected into widgets that have not declared an i18n features. Localizations within these widgets will not change as locales are updated over the event bus. Instead, they will simply use the default locale, as determined by the application configuration path `i18n.locales.default`.
