### ISSUE TITLE
AxAreaHelper: Add attribute `data-ax-widget-area` to widget areas

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#434]
Laxar should add the attribute `data-ax-widget-area` to the DOM element of a widget area to allow easy DOM inspection. Each widget area should have the attribute with its local name as value.

In further versions of the laxar-developer-tools it might be a nice feature to select widget area.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
