### ISSUE TITLE
Documentation: Fix link in the manual about the plain adapter

### ISSUE THREAD

**Issue by jonaswjs** [LaxarJS/laxar#451]
The name of the file is `widget_services.md` instead of `widgets_services.md`:

```
Preliminary readings:

* [LaxarJS Core Concepts](../concepts.md)
* [Widgets and Activities](widgets_and_activities.md)
* [Widgets Services](widgets_services.md)
```

https://raw.githubusercontent.com/LaxarJS/laxar/master/docs/manuals/plain_adapter.md
https://github.com/LaxarJS/laxar/blob/master/docs/manuals/widget_services.md

**Comment by x1B** [comment]
Fixed on `master` (`v2.0.0`).
