### ISSUE TITLE
bootstrapping: fix NPE when name is missing

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#452]
Trying to create an unnamed LaxarJS instance causes an NPE because `configuration.name` is assumed to always be defined.

**Comment by x1B** [comment]
@jpommerening FYI

**Comment by jpommerening** [comment]
Implemented on `master` (`v2.0.0`)

@x1B: do you need this to be published _now_ or should we wait?

**Comment by x1B** [comment]
@jpommerening I'd prefer ASAP because we'll be able to release pretty much nothing else before that :)

**Comment by x1B** [comment]
_(released, alpha 24)_
