### ISSUE TITLE
documentation: various small improvements

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#466]
Some items that I just stumbled upon in the _Widgets and Activities_ manual:

 - apparently, the indent of markdown lists needs to be fixed to look right not only on GitHub, but also on the docs site,
 - the manual lists various integration technologies, but does not include `angular` there,
 - in various places, there should be links to the widget adapter manuals, especially the `angular` adapter which is the basis for much of the manual.

**Comment by alex3683** [comment]
I propose using only `-` for list items and not `*`, not indenting the first level of list items. `*` can get confusing when used in API doc comments. Using `-` everywhere guarantees a consistent style.

**Comment by x1B** [comment]
Ok, I'll make it so.

**Comment by x1B** [comment]
Implemented on `master` (`v2.0.0`).
