### ISSUE TITLE
flow: self-navigation loses existing place parameters

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#469]
The following problem was observered in the [laxar-markdown-display-widget](https://github.com/LaxarJS/laxar-markdown-display-widget):

When using `constructAbsoluteUrl` with `_self` to update a URL parameter, previous values for other URL parameters are lost.

**Comment by x1B** [comment]
And by "other parameters" I mean any parameters that were not specified in the constructAbsoluteUrl call.

**Comment by x1B** [comment]
@jonaswjs assigning to you for a simplified reproduction

**Comment by jonaswjs** [comment]
I created the last-selected-article-widget in the shop-demo and added a second parameter to the flow definition to reproduce the error.

Steps to reproduce:
Clone the shop-demo and check out the branch: `feature/laxar-469-reproduce-bug`

In the running application search for `beer` and then select one of the remaining articles. The `last-selected-article-widget` displays the name of the last selected article, the value of the place parameter (of the link below) and a link which includes the place parameter of the last selected article. This link should include the place parameter of the search term too:
https://github.com/LaxarJS/shop-demo/blob/feature/laxar-469-reproduce-bug/application/widgets/last-selected-article-widget/last-selected-article-widget.vue#L50

**Comment by jonaswjs** [comment]
In the `laxar-markdown-display-widget` we fixed it with a work around:
https://github.com/LaxarJS/laxar-markdown-display-widget/issues/22
https://github.com/LaxarJS/laxar-markdown-display-widget/blob/master/laxar-markdown-display-widget.js#L37

The `laxar-markdown-display-widget` caches all parameters.

**Comment by x1B** [comment]
@jonaswjs interesting, I'll try to get to the bottom of this. Thanks for reproducing this.

**Comment by x1B** [comment]
Fixed on `master` (`v2.1.0`) and `release-2.0.x` (`v2.0.2`).
