### ISSUE TITLE
whenDocumentReady(): DOMContentLoaded small race condition

### ISSUE THREAD

**Issue by kmdm** [LaxarJS/laxar#472]
whenDocumentReady() has a small race condition which I'm hitting due to slightly non-standard use of the laxarjs generator generated project.

It uses document.readyState == 'complete' to determine if it should bind to DOMContentLoaded, however, these are not entirely equivalent:-

complete: "The document and all sub-resources have finished loading. The state indicates that the load event is about to fire."

DOMContentLoaded: "The DOMContentLoaded event is fired when the initial HTML document has been completely loaded and parsed, without waiting for stylesheets, images, and subframes to finish loading. A very different event load should be used only to detect a fully-loaded page."

Thus if the document readyState is currently 'interactive' it'll bind to DOMContentLoaded but the event could well have already fired thus it'll just yield a blank page waiting for an event which'll never arrive. 

The 'interactive' readyState matches the definition for DOMContentLoaded: "The document has finished loading and the document has been parsed but sub-resources such as images, stylesheets and frames are still loading."

Thus I believe that it should directly call ready() if the readyState is 'complete' or 'interactive' (or not 'loading').

**Comment by jpommerening** [comment]
Hi @kmdm! This is a nice catch!

And thanks for already digging through the sources and relevant specs to find the problematic code and a solution.
Your description sounds reasonable. When the browser runs into `whenDocumentReady` while the ready state is `interactive`, we miss `DOMContentLoaded` entirely, or so it seems.

You seem to be hitting this bug semi-reliably – can you send a reproduction so we can try this (and the fix) in a bunch of browsers?

We'll take a more thorough look tomorrow and should be able to ship a patch version in no time!

**Comment by kmdm** [comment]
Basically... rightly or wrongly since I've not got myself fully up to speed with laxar yet I'm calling the create(...)...bootstrap() from inside an Ajax success/fail handler. Most of the time it hit that function with the state at 'interactive'.

(I'm wanting to dynamically create flows/pages... Ajaxing and merging artifacts seemed /a way/ of doing it... if not a completely stupid one. I couldn't find another way of dynamically adding pages/flows yet anyway.)

**Comment by jpommerening** [comment]
It's good to hear we're not the only ones who want to dynamically load flows/pages/widgets into a running application! As of now, it is not possible to add artifacts _after_ `bootstrap` has been called. You should definitely keep an eye on #363 if you're interested in that!

Merging multiple artifacts bundles _before_ calling `bootstrap` could be possible, but keep in mind that the `artifacts` parameter is more than a list of flow.json, page.json contents. It actually contains everything that makes up your application, including widget modules and all their dependencies. You might run into some issues there.
Just for fun, I tried to do that in a branch of our demo project: https://github.com/LaxarJS/shop-demo/tree/experiment-fetch-artifacts-async (have a look at `init.js` and the `webpack.config.js`)

Back to the original issue: yes, we think we should also call the `ready` function when the ready state at that point equals `'interactive'`

**Comment by jpommerening** [comment]
@kmdm I just reproduced the issue in Firefox with the branch I mentioned earlier! 🎉

Synchronously initializing while in `interactive` state seems to work just fine, so I'll follow your suggestion and fix the condition as you described!

We'd love to hear what you've done with LaxarJS until now! Have you had a look at the [tutorial](https://github.com/LaxarJS/shop-demo/blob/master-2.x/docs/tutorials/01_getting_started.md#getting-started)? Also, you might want to have a look at the [concepts](http://laxarjs.org/docs/laxar-latest/concepts/) behind a LaxarJS application. We're aware there's a learning curve and as a developer I feel these things help to understand how the parts fit together :)

**Comment by kmdm** [comment]
@jpommerening Good to hear and thanks for the prompt fix/commit.

We're looking at an application where we provide widgets and predefined flows/page layouts but user's are able to combine the widgets onto the page as they see fit (and save/generate their own layouts)... which reads to me like dynamically creating flows/pages and adding/removing widgets from the page. Layout is obviously our problem but the rest seems to be in laxar's domain. 

So I guess I need to follow/wait for #363 (and hope it includes pages/flows).

**Comment by jpommerening** [comment]
The fix has just been released with `v2.0.1`

I'll close this issue, but feel free to get in touch if you need any assistance. We're here to help!
