### ISSUE TITLE
portal: create controller injections on demand (was: create adapter for AngularJS activities)

### ISSUE THREAD

**Issue by x1B** [LaxarJS/laxar#71]
Activities do not need a scope, but might need other AngularJS-style injections (e.g. eventBus, $q, etc.). We should provide an adapter to do this, parallel to the AngularJS widget adapter. Having fewer scopes should enhance performance in some cases.

**Comment by x1B** [comment]
_Better idea:_ Using `Object.defineProperty` we can create _all_ injections lazily!

**Comment by alex3683** [comment]
Implemented on `master` (`v1.0.0`).
