### ISSUE TITLE
Evaluate "flattening" the themes

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#74]
I want to propose changing the way themes are built in a way that is "mostly compatible" with what we have now.

**Warning:** this issue contains lots of samples. [>> fast-forward](#user-content-tl-dr)

Currently a theme consists of many CSS files; one for each widget and each control that needs application-specific styling. These files are generated from `.scss` files, so we end up with something like this:

```
sample.theme
├── css/theme.css
├── scss/theme.scss
├─┬ widgets
│ └─┬ sample
│   ├─┬ my_first_widget
│   │  ├─ css/my_first_widget.css
│   │  └─ scss/my_first_widget.scss
│   ├─┬ my_second_widget
│   │  ├─ css/my_second_widget.css
│   │  └─ scss/my_second_widget.scss
│   └─┬ my_third_widget
│      ├─ css/my_third_widget.css
│      └─ scss/my_third_widget.scss
└── laxar_uikit
  └─┬ controls
    ├─┬ accordion
    │  ├─ css/accordion.css
    │  └─ scss/accordion.scss
    └─┬ date_picker
       ├─ css/date_picker.css
       └─ scss/date_picker.scss
```

If we assume that you usually don't add stylesheets for what you don't use (a reasonable assumption, IMHO) it should suffice to create _just one_ CSS file per theme that contains _everything_. Since we use Sass/Compass we can still split the development into bite-sized chunks:

```
sample.theme
├── css/theme.css
├── scss/theme.scss
├─┬ widgets
│ └─┬ sample
│   ├─┬ my_first_widget
│   │  └─ scss/_my_first_widget.scss
│   ├─┬ my_second_widget
│   │  └─ scss/_my_second_widget.scss
│   └─┬ my_third_widget
│      └─ scss/_my_third_widget.scss
└── laxar_uikit
  └─┬ controls
    ├─┬ accordion
    │  └─ scss/_accordion.scss
    └─┬ date_picker
       └─ scss/_date_picker.scss
```

That should _already_ be possible, since application-specific styling is entirely optional and the missing CSS files should be of no concern. All we have to do is rename the widget- and control-specific files to have a leading underscore and include them in the "main" SCSS file, like so:

```scss
@import "../widgets/sample/my_first_widget/scss/my_first_widget";
@import "../widgets/sample/my_first_widget/scss/my_second_widget";
@import "../widgets/sample/my_first_widget/scss/my_second_widget";
@import "../laxar_uikit/controls/accordion/scss/accordion";
@import "../laxar_uikit/controls/date_picker/scss/date_picker";
```

Granted, these paths look a little bit awkward, let's improve on that, by moving the `widgets` and `laxar_uikit` directories into the `scss` directory and cutting some layers:

(Note: this part is completely in the hands of the person developing the theme)
```
sample.theme
├── css/theme.css
└─┬ scss/theme.scss
  ├─┬ widgets
  │ └─┬ sample
  │   ├─┬ my_first_widget
  │   │  └─ _my_first_widget.scss
  │   ├─┬ my_second_widget
  │   │  └─ _my_second_widget.scss
  │   └─┬ my_third_widget
  │      └─ _my_third_widget.scss
  └── laxar_uikit
    └─┬ controls
      ├─┬ accordion
      │  └─ _accordion.scss
      └─┬ date_picker
         └─ _date_picker.scss
```

After some fiddling with sprite- and image-paths in the `config.rb`, we should be able to write something, that nicely mirrors the directory layout we expect for widgets' and controls' JavaScript files:
```scss
@import "widgets/sample/my_first_widget/my_first_widget";
@import "widgets/sample/my_first_widget/my_second_widget";
@import "widgets/sample/my_first_widget/my_second_widget";
@import "laxar_uikit/controls/accordion/accordion";
@import "laxar_uikit/controls/date_picker/date_picker";
```

<a name="tl-dr"/>**TL;DR**: I believe most, if not all, of the required changes are entirely up to the theme author. This _should_ work without any changes to _ThemeLoader_ et. al.
I'm just asking if anyone of you sees any downsides to this approach. Maybe there's something I missed. If this works as expected, should we promote this as the "one true way" to developing themes?

/cc @alex3683, @x1B

**Comment by x1B** [comment]
Let's archive this issue for now. Most of the grunt infrastructure has changed, and the requirement for individual CSS artifact still exists.

To make life easier for SCSS authort, we might want to write a new task that integrates with the artifacts listing now provided by grunt-laxar to monitor SCSS files and trigger their recompilation.
