### ISSUE TITLE
Evaluate updating spec_runner.html to load a different require_config.js

### ISSUE THREAD

**Issue by jpommerening** [LaxarJS/laxar#78]
This is mostly just relevant for the `spec_runner.html` files in LaxarJS (core, uikit, patterns) but the changes should not break anything if applied elsewhere.

We should try to update the `spec_runner.html` files so that it's possible to override the require config location when running in an iframe.
We're embedding these pages in our demo/booklet app and because of that we have to `bower install` in all laxar submodules just to get the tests running.
It should be possible to run the tests with the require configuration of the product.

I don't know if this is somehow possible, but if there's a way to get this to work we should do it, because it would save quite some time setting up the booklet application.

**Comment by x1B** [comment]
Implemented on `master` (`v1.1.0`).

### Upgrade Information

The HTML spec runners (browser only) now allow to specify where to look for the `require_config.js`. This allows to run the LaxarJS spec tests from within a product to:

   * improve conveniece
   * help to identify possible conflicts between LaxarJS and  the project's configuration

By default, the configuration will be searched as if _laxar_ was installed at `includes/lib/laxar`. To use a different location, pass the URL parameter `folderDepth={x}` to the spec-runner, where `x` is the number of URL segment to go upwards for finding the `require_config.js`.
